[package]
name = "academy-workstation2-course"
version.workspace = true
edition.workspace = true
publish.workspace = true
description = "Touchscreen workstation development course for TrueLearner Academy"

[dependencies]
academy-workstation2.workspace = true
serde.workspace = true
truelearner-workstation.workspace = true

[lib]
path = "src/lib.rs"
