[package]
name = "organism-v0"
version = "0.1.0"
edition = "2021"
default-run = "organism-v0"

[workspace]
members = [
    "crates/frozen-organism-v1-physics",
    "crates/px0-physical-correspondence",
]
default-members = ["crates/frozen-organism-v1-physics"]
resolver = "2"

[dependencies]
frozen-organism-v1-physics = { path = "crates/frozen-organism-v1-physics" }

[profile.test]
opt-level = 2
