[package]
name = "academy-playground"
version.workspace = true
edition.workspace = true
publish.workspace = true
description = "Dioxus Desktop developmental environment for TrueLearner"

[[bin]]
name = "academy"
path = "src/main.rs"

[dependencies]
academy-core.workspace = true
base64.workspace = true
dioxus = { workspace = true, features = ["desktop", "lib", "launch"] }
futures-timer.workspace = true
